const paper2Questions = [
  // THEORY OF COMPUTATION (24 Questions)
  { "id": "TOC_1", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "Which of the following is the most restricted class of languages in the Chomsky hierarchy?", "options": ["Context-Free Languages", "Regular Languages", "Context-Sensitive Languages", "Recursively Enumerable Languages"], "answer": "b", "explanation": "Regular languages are generated by Type-3 grammars and are the most restricted in the Chomsky hierarchy.", "difficulty": "Easy" },
  { "id": "TOC_2", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "If L is a Regular Language, which of the following must also be true?", "options": ["L is not a CFL", "L is a DCFL", "L requires a Turing Machine", "L cannot be recognized by a PDA"], "answer": "b", "explanation": "Regular ⊂ DCFL ⊂ CFL. Any regular language is automatically a Deterministic Context-Free Language.", "difficulty": "Medium" },
  { "id": "TOC_3", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "Which language class is recognized by a Linear Bounded Automaton?", "options": ["Regular", "Context-Free", "Context-Sensitive", "Recursive"], "answer": "c", "explanation": "Context-Sensitive Languages (Type-1) are accepted by Linear Bounded Automata (LBA).", "difficulty": "Easy" },
  { "id": "TOC_4", "section": "Theory of Computation", "topic": "Grammar Rules", "question": "Which of the following productions is valid in a strictly Right-Linear grammar?", "options": ["A → aB", "A → Ba", "A → aBa", "A → AB"], "answer": "a", "explanation": "In a Right-Linear grammar, the non-terminal must appear strictly at the right end of the production.", "difficulty": "Medium" },
  { "id": "TOC_5", "section": "Theory of Computation", "topic": "Grammar Rules", "question": "Every Regular Grammar is necessarily a:", "options": ["Context-Sensitive Grammar only", "Context-Free Grammar", "Type-0 Grammar only", "None of the above"], "answer": "b", "explanation": "Since Regular languages are a subset of CFLs, all Regular grammars fall under Context-Free grammars.", "difficulty": "Easy" },
  { "id": "TOC_6", "section": "Theory of Computation", "topic": "Pushdown Automata", "question": "The transition function of an NPDA depends on the current state, input symbol, and:", "options": ["Next state", "Entire stack content", "Top of stack symbol", "Tape marker"], "answer": "c", "explanation": "An NPDA transitions based on (State, Input Symbol, Top of Stack).", "difficulty": "Easy" },
  { "id": "TOC_7", "section": "Theory of Computation", "topic": "Pushdown Automata", "question": "Which of the following languages requires a Non-Deterministic Pushdown Automaton (NPDA) and cannot be accepted by a DPDA?", "options": ["a^nb^n", "wcw^R", "ww^R", "a^*b^*"], "answer": "c", "explanation": "Even-length palindromes (ww^R) lack a middle marker, requiring non-determinism to guess the midpoint.", "difficulty": "Medium" },
  { "id": "TOC_8", "section": "Theory of Computation", "topic": "Turing Machines", "question": "A language is called Recursive if there exists a Turing Machine that:", "options": ["Loops infinitely on some inputs", "Halts and accepts valid strings, but may loop on invalid ones", "Always halts and decides the language", "Only uses a finite length tape"], "answer": "c", "explanation": "Recursive languages are decidable; the TM will always halt whether it accepts or rejects.", "difficulty": "Medium" },
  { "id": "TOC_9", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "Which of the following is true regarding Context-Free Languages (CFL)?", "options": ["CFLs are closed under intersection", "CFLs are closed under complementation", "CFLs are closed under union", "CFLs are closed under difference"], "answer": "c", "explanation": "CFLs are closed under union, concatenation, and Kleene star, but NOT intersection or complementation.", "difficulty": "Hard" },
  { "id": "TOC_10", "section": "Theory of Computation", "topic": "Grammar Rules", "question": "Which grammar type corresponds to Recursively Enumerable languages?", "options": ["Type 0", "Type 1", "Type 2", "Type 3"], "answer": "a", "explanation": "Type 0 (Unrestricted Grammars) generate Recursively Enumerable languages.", "difficulty": "Easy" },
  { "id": "TOC_11", "section": "Theory of Computation", "topic": "Pushdown Automata", "question": "A PDA with two stacks is computationally equivalent to a:", "options": ["Finite Automaton", "Linear Bounded Automaton", "Turing Machine", "Non-Deterministic PDA"], "answer": "c", "explanation": "A PDA augmented with a second stack gains the full computational power of a Turing Machine.", "difficulty": "Hard" },
  { "id": "TOC_12", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "The language L = {a^n b^n c^n | n ≥ 1} belongs to which class?", "options": ["Regular", "Context-Free", "Context-Sensitive", "Finite"], "answer": "c", "explanation": "A PDA cannot count three distinct equal variables, but an LBA (Context-Sensitive) can.", "difficulty": "Medium" },
  { "id": "TOC_13", "section": "Theory of Computation", "topic": "Automata Transitions", "question": "The pumping lemma for regular languages is generally used to prove that a language is:", "options": ["Regular", "Context-Free", "Not Regular", "Decidable"], "answer": "c", "explanation": "Pumping lemmas are adversarial proofs used specifically to show a language falls outside a given class.", "difficulty": "Medium" },
  { "id": "TOC_14", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "If L1 and L2 are regular languages, which operation might NOT result in a regular language?", "options": ["L1 ∪ L2", "L1 ∩ L2", "L1' (Complement)", "None, all remain regular"], "answer": "d", "explanation": "Regular languages are closed under all basic operations: union, intersection, and complement.", "difficulty": "Easy" },
  { "id": "TOC_15", "section": "Theory of Computation", "topic": "Grammar Rules", "question": "The production S → aSb | ε generates which language?", "options": ["a^* b^*", "a^n b^n", "Palindromes", "Strings with equal a's and b's in any order"], "answer": "b", "explanation": "It generates matching a's and b's from the outside in, yielding a^n b^n.", "difficulty": "Easy" },
  { "id": "TOC_16", "section": "Theory of Computation", "topic": "Turing Machines", "question": "The Halting Problem for Turing Machines is:", "options": ["Decidable", "Undecidable", "Regular", "Context-Free"], "answer": "b", "explanation": "Alan Turing proved that no general algorithm can determine if every possible TM halts.", "difficulty": "Easy" },
  { "id": "TOC_17", "section": "Theory of Computation", "topic": "Pushdown Automata", "question": "Which of the following can a Deterministic Finite Automaton (DFA) do?", "options": ["Count arbitrarily high", "Recognize palindromes", "Remember a finite amount of state information", "Reverse a string"], "answer": "c", "explanation": "DFAs have no memory other than their finite set of states.", "difficulty": "Easy" },
  { "id": "TOC_18", "section": "Theory of Computation", "topic": "Automata Transitions", "question": "To convert an NFA to a DFA, the standard algorithm used is:", "options": ["Subset Construction", "Thompson's Construction", "CYK Algorithm", "Myhill-Nerode Theorem"], "answer": "a", "explanation": "Subset construction (powerset construction) converts NFA states into subsets representing DFA states.", "difficulty": "Medium" },
  { "id": "TOC_19", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "Is the complement of a Recursive language always Recursive?", "options": ["Yes", "No", "Only if it is also CFL", "Only if the alphabet is binary"], "answer": "a", "explanation": "Recursive languages are closed under complementation because the TM can simply flip its accept/reject state.", "difficulty": "Medium" },
  { "id": "TOC_20", "section": "Theory of Computation", "topic": "Grammar Rules", "question": "Chomsky Normal Form (CNF) requires all productions to be of the form:", "options": ["A → BC or A → a", "A → aB or A → a", "A → a or A → ε", "A → Ba or A → b"], "answer": "a", "explanation": "In CNF, every rule must map to either two non-terminals or a single terminal.", "difficulty": "Medium" },
  { "id": "TOC_21", "section": "Theory of Computation", "topic": "Pushdown Automata", "question": "A PDA accepts a string if, after reading the entire input, it ends in an accepting state OR:", "options": ["The tape is blank", "The stack is empty", "It reaches the start state", "The stack size is exactly 1"], "answer": "b", "explanation": "PDAs can accept by final state OR by empty stack.", "difficulty": "Easy" },
  { "id": "TOC_22", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "Which machine has a read-only tape that can only move in one direction?", "options": ["Turing Machine", "Linear Bounded Automaton", "Finite Automaton", "Pushdown Automaton"], "answer": "c", "explanation": "Standard Finite Automata read input sequentially left-to-right without modifying it.", "difficulty": "Easy" },
  { "id": "TOC_23", "section": "Theory of Computation", "topic": "Turing Machines", "question": "A Universal Turing Machine can be thought of as:", "options": ["A hardware CPU executing an OS", "A programmable computer that can simulate any TM", "An automaton without a halt state", "A machine that only processes regular expressions"], "answer": "b", "explanation": "A UTM reads the description of another TM and simulates its behavior on an input.", "difficulty": "Medium" },
  { "id": "TOC_24", "section": "Theory of Computation", "topic": "Language Hierarchy", "question": "Which hierarchy class contains the language of all valid C programs?", "options": ["Regular", "Context-Free", "Context-Sensitive", "It is not a formal language"], "answer": "b", "explanation": "Programming language syntax is generally defined by Context-Free Grammars.", "difficulty": "Medium" },

  // DATABASE MANAGEMENT SYSTEMS (22 Questions)
  { "id": "DBMS_1", "section": "DBMS", "topic": "Integrity Constraints", "question": "Entity Integrity implies that:", "options": ["Primary keys cannot be NULL", "Foreign keys cannot be NULL", "Table names must be unique", "Columns must have unique data types"], "answer": "a", "explanation": "Entity integrity ensures every row is identifiable, forbidding NULL primary keys.", "difficulty": "Easy" },
  { "id": "DBMS_2", "section": "DBMS", "topic": "Integrity Constraints", "question": "Referential integrity requires that:", "options": ["All primary keys are integers", "A foreign key must either match a primary key or be NULL", "A table can only have one foreign key", "Every table must have a foreign key"], "answer": "b", "explanation": "Foreign keys must point to an existing valid primary key in the parent table or be NULL.", "difficulty": "Medium" },
  { "id": "DBMS_3", "section": "DBMS", "topic": "ER Diagrams", "question": "In an ER diagram, a derived attribute is represented by a:", "options": ["Double ellipse", "Dashed/dotted ellipse", "Rectangle", "Diamond"], "answer": "b", "explanation": "Derived attributes (e.g., age calculated from birth date) use dashed ellipses.", "difficulty": "Easy" },
  { "id": "DBMS_4", "section": "DBMS", "topic": "ER Diagrams", "question": "A weak entity set in an ER diagram is enclosed in a:", "options": ["Single rectangle", "Double rectangle", "Diamond", "Ellipse"], "answer": "b", "explanation": "Weak entities depend on a strong owner entity and are drawn with double rectangles.", "difficulty": "Easy" },
  { "id": "DBMS_5", "section": "DBMS", "topic": "SQL Clauses", "question": "Which of the following clauses is completely optional for a valid SQL retrieval query?", "options": ["SELECT", "FROM", "WHERE", "Both SELECT and FROM"], "answer": "c", "explanation": "SELECT and FROM extract the data; WHERE is only needed to filter it.", "difficulty": "Easy" },
  { "id": "DBMS_6", "section": "DBMS", "topic": "Normalization", "question": "A relation is in 2NF if and only if it is in 1NF and:", "options": ["No partial dependencies exist", "No transitive dependencies exist", "It has no multi-valued attributes", "Every determinant is a candidate key"], "answer": "a", "explanation": "2NF eliminates partial dependencies (non-prime attributes depending on part of a composite key).", "difficulty": "Medium" },
  { "id": "DBMS_7", "section": "DBMS", "topic": "Normalization", "question": "Which normal form deals specifically with eliminating transitive dependencies?", "options": ["1NF", "2NF", "3NF", "BCNF"], "answer": "c", "explanation": "3NF ensures that non-key attributes do not depend on other non-key attributes.", "difficulty": "Medium" },
  { "id": "DBMS_8", "section": "DBMS", "topic": "Transactions", "question": "The ACID property ensuring that a transaction executes completely or not at all is:", "options": ["Atomicity", "Consistency", "Isolation", "Durability"], "answer": "a", "explanation": "Atomicity means 'all or nothing' execution of a transaction.", "difficulty": "Easy" },
  { "id": "DBMS_9", "section": "DBMS", "topic": "Transactions", "question": "Which ACID property guarantees that once a transaction commits, its changes survive crashes?", "options": ["Atomicity", "Consistency", "Isolation", "Durability"], "answer": "d", "explanation": "Durability stores committed changes permanently to non-volatile storage.", "difficulty": "Easy" },
  { "id": "DBMS_10", "section": "DBMS", "topic": "Relational Algebra", "question": "In Relational Algebra, the Projection (π) operator selects:", "options": ["Specific rows", "Specific columns", "Matching foreign keys", "Cartesian products"], "answer": "b", "explanation": "Projection (π) acts like SELECT in SQL, choosing vertical columns. Selection (σ) chooses rows.", "difficulty": "Easy" },
  { "id": "DBMS_11", "section": "DBMS", "topic": "Relational Algebra", "question": "If a Selection (σ) operation is applied without a Projection (π), what happens?", "options": ["Only the primary key is returned", "An error occurs", "All columns for matching rows are returned", "No rows are returned"], "answer": "c", "explanation": "Selection alone returns the entire tuple (all columns) for rows meeting the condition.", "difficulty": "Medium" },
  { "id": "DBMS_12", "section": "DBMS", "topic": "ER Diagrams", "question": "A double-lined diamond in an ER diagram represents:", "options": ["A ternary relationship", "An identifying relationship", "A weak entity", "A total participation constraint"], "answer": "b", "explanation": "Identifying relationships connect a weak entity to its strong owner entity.", "difficulty": "Medium" },
  { "id": "DBMS_13", "section": "DBMS", "topic": "SQL Clauses", "question": "Which SQL clause is used to filter the results of a GROUP BY clause?", "options": ["WHERE", "HAVING", "ORDER BY", "FILTER"], "answer": "b", "explanation": "WHERE filters before grouping; HAVING filters after grouping.", "difficulty": "Easy" },
  { "id": "DBMS_14", "section": "DBMS", "topic": "Transactions", "question": "A deadlock occurs in a DBMS when:", "options": ["A transaction commits", "Two transactions wait indefinitely for each other's locks", "A disk fails during write", "A query takes too long"], "answer": "b", "explanation": "Deadlock is a circular wait condition involving multiple transactions.", "difficulty": "Easy" },
  { "id": "DBMS_15", "section": "DBMS", "topic": "Normalization", "question": "BCNF (Boyce-Codd Normal Form) is a stricter version of:", "options": ["1NF", "2NF", "3NF", "4NF"], "answer": "c", "explanation": "BCNF requires that for every non-trivial dependency X → Y, X must be a superkey.", "difficulty": "Medium" },
  { "id": "DBMS_16", "section": "DBMS", "topic": "Integrity Constraints", "question": "Which SQL keyword enforces domain integrity on a column?", "options": ["UNIQUE", "CHECK", "PRIMARY KEY", "FOREIGN KEY"], "answer": "b", "explanation": "The CHECK constraint ensures values in a column meet specific logical conditions.", "difficulty": "Medium" },
  { "id": "DBMS_17", "section": "DBMS", "topic": "SQL Clauses", "question": "To sort the result set in descending order, SQL uses the keyword:", "options": ["DESC", "DOWN", "SORT", "REVERSE"], "answer": "a", "explanation": "ORDER BY column_name DESC sorts the data in descending order.", "difficulty": "Easy" },
  { "id": "DBMS_18", "section": "DBMS", "topic": "Transactions", "question": "The process of undoing a partially completed transaction is called:", "options": ["Commit", "Rollback", "Flush", "Checkpoint"], "answer": "b", "explanation": "Rollback reverts the database to its state before the transaction began.", "difficulty": "Easy" },
  { "id": "DBMS_19", "section": "DBMS", "topic": "Relational Algebra", "question": "The Cartesian Product of two relations with cardinalities M and N will have how many tuples?", "options": ["M + N", "M - N", "M * N", "M / N"], "answer": "c", "explanation": "Cartesian product multiplies the rows, yielding M * N combinations.", "difficulty": "Medium" },
  { "id": "DBMS_20", "section": "DBMS", "topic": "ER Diagrams", "question": "A multi-valued attribute in an ER diagram is drawn as:", "options": ["A dashed ellipse", "A double ellipse", "A double rectangle", "A diamond"], "answer": "b", "explanation": "Attributes that can hold multiple values (like phone numbers) use a double ellipse.", "difficulty": "Easy" },
  { "id": "DBMS_21", "section": "DBMS", "topic": "SQL Clauses", "question": "Which command permanently removes a table's structure and data from the database?", "options": ["DELETE", "TRUNCATE", "DROP", "REMOVE"], "answer": "c", "explanation": "DROP TABLE destroys the schema and data. TRUNCATE only removes data.", "difficulty": "Medium" },
  { "id": "DBMS_22", "section": "DBMS", "topic": "Integrity Constraints", "question": "A candidate key is a:", "options": ["Minimal superkey", "Foreign key", "Composite primary key", "Null key"], "answer": "a", "explanation": "A candidate key is a superkey from which no attribute can be removed without losing the uniqueness property.", "difficulty": "Hard" },

  // OPERATING SYSTEMS (20 Questions)
  { "id": "OS_1", "section": "Operating Systems", "topic": "Process States", "question": "The 'Ready' queue of processes is maintained in which memory location?", "options": ["Secondary Memory", "Primary Memory (RAM)", "Cache", "CPU Registers"], "answer": "b", "explanation": "Active states like Ready, Running, and Waiting reside in Primary Memory.", "difficulty": "Easy" },
  { "id": "OS_2", "section": "Operating Systems", "topic": "Process States", "question": "When a process is first created, it enters which state?", "options": ["Ready", "Running", "New", "Waiting"], "answer": "c", "explanation": "Newly spawned processes sit in the 'New' state in secondary memory before admission.", "difficulty": "Easy" },
  { "id": "OS_3", "section": "Operating Systems", "topic": "Schedulers", "question": "Which scheduler is also known as the Job Scheduler?", "options": ["Short-Term Scheduler", "Mid-Term Scheduler", "Long-Term Scheduler", "I/O Scheduler"], "answer": "c", "explanation": "The Long-Term Scheduler dictates the degree of multiprogramming by moving jobs from New to Ready.", "difficulty": "Medium" },
  { "id": "OS_4", "section": "Operating Systems", "topic": "Schedulers", "question": "Which scheduler selects a process from the Ready queue to execute on the CPU?", "options": ["Short-Term Scheduler", "Mid-Term Scheduler", "Long-Term Scheduler", "Dispatch Scheduler"], "answer": "a", "explanation": "The Short-Term Scheduler (CPU Scheduler) makes frequent execution decisions.", "difficulty": "Easy" },
  { "id": "OS_5", "section": "Operating Systems", "topic": "System Calls", "question": "A user program requests a service from the OS kernel using a:", "options": ["System Call", "Context Switch", "Thread spawn", "Page fault"], "answer": "a", "explanation": "System calls act as the API bridge transitioning from user mode to kernel mode.", "difficulty": "Easy" },
  { "id": "OS_6", "section": "Operating Systems", "topic": "Memory Management", "question": "If Logical Address Space is 4096 and page size is 512, how many bits represent the page number?", "options": ["12", "9", "3", "4"], "answer": "c", "explanation": "2^12 = 4096 (12 total bits). 2^9 = 512 (9 offset bits). 12 - 9 = 3 bits for page number.", "difficulty": "Medium" },
  { "id": "OS_7", "section": "Operating Systems", "topic": "Memory Management", "question": "What is the primary purpose of a File Allocation Table (FAT)?", "options": ["To index disk blocks for files", "To schedule CPU time", "To encrypt user data", "To manage virtual memory pages"], "answer": "a", "explanation": "FAT maintains entries indexing which physical disk blocks belong to which files.", "difficulty": "Medium" },
  { "id": "OS_8", "section": "Operating Systems", "topic": "Deadlocks", "question": "Which of the following is NOT a necessary condition for Deadlock?", "options": ["Mutual Exclusion", "Hold and Wait", "Preemption", "Circular Wait"], "answer": "c", "explanation": "No Preemption is a necessary condition. If resources can be preempted, deadlocks can be broken.", "difficulty": "Medium" },
  { "id": "OS_9", "section": "Operating Systems", "topic": "Process States", "question": "A process moves from 'Running' to 'Waiting' when:", "options": ["Its time slice expires", "It finishes execution", "It requests I/O", "It is dispatched by the CPU"], "answer": "c", "explanation": "I/O operations block the CPU, moving the process to the Waiting (Blocked) state.", "difficulty": "Easy" },
  { "id": "OS_10", "section": "Operating Systems", "topic": "Schedulers", "question": "Swapping out processes to disk to free up RAM is handled by the:", "options": ["Long-Term Scheduler", "Mid-Term Scheduler", "Short-Term Scheduler", "Dispatcher"], "answer": "b", "explanation": "The Mid-Term Scheduler manages swapping to control thrashing.", "difficulty": "Medium" },
  { "id": "OS_11", "section": "Operating Systems", "topic": "System Calls", "question": "Which system call creates a new child process in Unix/Linux?", "options": ["exec()", "fork()", "spawn()", "wait()"], "answer": "b", "explanation": "fork() creates an exact duplicate of the calling process.", "difficulty": "Easy" },
  { "id": "OS_12", "section": "Operating Systems", "topic": "Memory Management", "question": "Internal fragmentation is most commonly a problem in:", "options": ["Paging", "Segmentation", "Contiguous allocation", "Demand Paging"], "answer": "a", "explanation": "Paging gives fixed-size blocks. If a process needs less than a full page, the remainder is wasted internally.", "difficulty": "Medium" },
  { "id": "OS_13", "section": "Operating Systems", "topic": "Memory Management", "question": "Translation Lookaside Buffer (TLB) is used to:", "options": ["Increase disk speed", "Cache recent page table translations", "Handle deadlocks", "Buffer I/O streams"], "answer": "b", "explanation": "The TLB is a high-speed cache for page table entries, speeding up logical-to-physical address mapping.", "difficulty": "Medium" },
  { "id": "OS_14", "section": "Operating Systems", "topic": "Deadlocks", "question": "Banker's Algorithm is used for:", "options": ["Deadlock Prevention", "Deadlock Avoidance", "Deadlock Detection", "Deadlock Recovery"], "answer": "b", "explanation": "Banker's Algorithm safely simulates resource allocation to avoid entering an unsafe state.", "difficulty": "Hard" },
  { "id": "OS_15", "section": "Operating Systems", "topic": "Schedulers", "question": "Round Robin scheduling inherently prevents:", "options": ["Starvation", "Context Switching", "Deadlock", "Interrupts"], "answer": "a", "explanation": "Because every process gets a time slice, no process can starve infinitely waiting for the CPU.", "difficulty": "Medium" },
  { "id": "OS_16", "section": "Operating Systems", "topic": "Memory Management", "question": "A page fault occurs when:", "options": ["A process divides by zero", "The requested page is not in RAM", "The CPU cache is full", "Two processes share memory"], "answer": "b", "explanation": "A page fault traps to the OS when a required virtual page is currently on disk instead of RAM.", "difficulty": "Easy" },
  { "id": "OS_17", "section": "Operating Systems", "topic": "System Calls", "question": "Transitions from user mode to kernel mode are typically triggered by:", "options": ["System calls and interrupts", "Function calls", "Loops", "Variable declarations"], "answer": "a", "explanation": "Hardware interrupts and software traps (system calls) set the mode bit to kernel.", "difficulty": "Medium" },
  { "id": "OS_18", "section": "Operating Systems", "topic": "Process States", "question": "What data structure does the OS use to store information about an active process?", "options": ["Process Control Block (PCB)", "File Allocation Table (FAT)", "Page Table", "Inode"], "answer": "a", "explanation": "The PCB stores state, registers, PID, and memory info for a process.", "difficulty": "Easy" },
  { "id": "OS_19", "section": "Operating Systems", "topic": "Deadlocks", "question": "Resource allocation graphs can detect deadlocks if:", "options": ["There are no cycles", "There is a cycle and single instances of each resource", "All processes are running", "Memory is fragmented"], "answer": "b", "explanation": "If every resource type has only one instance, a cycle in the RAG implies a deadlock.", "difficulty": "Hard" },
  { "id": "OS_20", "section": "Operating Systems", "topic": "Memory Management", "question": "The time it takes for a disk arm to move to the correct cylinder is called:", "options": ["Rotational Latency", "Seek Time", "Transfer Time", "Access Time"], "answer": "b", "explanation": "Seek time is the mechanical movement of the read/write head to the desired track/cylinder.", "difficulty": "Easy" },

  // COA (18 Questions)
  { "id": "COA_1", "section": "COA", "topic": "Cache Memory", "question": "Which memory type is physically located closest to the CPU execution units?", "options": ["Main Memory", "Cache Memory", "Registers", "Secondary Storage"], "answer": "c", "explanation": "Registers are internal to the CPU and operate at the processor's core clock speed.", "difficulty": "Easy" },
  { "id": "COA_2", "section": "COA", "topic": "Pipelining", "question": "Once a k-stage pipeline is completely filled, what is the ideal throughput?", "options": ["k instructions per cycle", "1 instruction per k cycles", "1 instruction per clock cycle", "k^2 instructions per cycle"], "answer": "c", "explanation": "A filled pipeline retires one instruction every clock cycle, regardless of the number of stages.", "difficulty": "Medium" },
  { "id": "COA_3", "section": "COA", "topic": "Instruction Formats", "question": "In a 3-address instruction format (e.g., ADD R1, R2, R3), the operands can be:", "options": ["Only registers", "Only memory addresses", "Registers or memory locations", "Immediate values only"], "answer": "c", "explanation": "Depending on the architecture, operands can be any combination of memory and registers.", "difficulty": "Easy" },
  { "id": "COA_4", "section": "COA", "topic": "Addressing Modes", "question": "In Register Addressing Mode, where is the operand located?", "options": ["Inside the instruction itself", "In main memory", "Inside a CPU register", "On the stack"], "answer": "c", "explanation": "The instruction contains the name/address of the register holding the data.", "difficulty": "Easy" },
  { "id": "COA_5", "section": "COA", "topic": "Digital Logic", "question": "If a combinational circuit adds two 3-bit numbers, what is the minimum number of output bits required?", "options": ["3", "4", "5", "6"], "answer": "b", "explanation": "Max value of 3-bits is 7. 7+7 = 14. 14 requires 4 bits (1110).", "difficulty": "Medium" },
  { "id": "COA_6", "section": "COA", "topic": "Cache Memory", "question": "Locality of reference fundamentally justifies the existence of:", "options": ["Interrupts", "Virtual Memory", "Cache Memory", "Pipelining"], "answer": "c", "explanation": "Cache memory exploits temporal and spatial locality to speed up CPU data access.", "difficulty": "Easy" },
  { "id": "COA_7", "section": "COA", "topic": "Addressing Modes", "question": "Which addressing mode is primarily used for implementing arrays and loops?", "options": ["Immediate", "Direct", "Indexed", "Register Indirect"], "answer": "c", "explanation": "Indexed addressing mode adds an index register value to a base address, perfect for arrays.", "difficulty": "Medium" },
  { "id": "COA_8", "section": "COA", "topic": "Pipelining", "question": "Which type of pipeline hazard is caused by data dependencies between instructions?", "options": ["Structural Hazard", "Control Hazard", "Data Hazard", "Branch Hazard"], "answer": "c", "explanation": "Data hazards happen when an instruction needs the result of a previous, unfinished instruction.", "difficulty": "Easy" },
  { "id": "COA_9", "section": "COA", "topic": "Pipelining", "question": "Control hazards in pipelines are typically caused by:", "options": ["ALU limitations", "Cache misses", "Branch instructions", "Register forwarding"], "answer": "c", "explanation": "Branch instructions alter the flow of control, making fetched instructions invalid.", "difficulty": "Medium" },
  { "id": "COA_10", "section": "COA", "topic": "Instruction Formats", "question": "The Opcode field in an instruction format specifies:", "options": ["Where to store the result", "The operation to be performed", "The addressing mode", "The next instruction address"], "answer": "b", "explanation": "Operation Code (Opcode) tells the CPU what action to take (ADD, SUB, LOAD, etc.).", "difficulty": "Easy" },
  { "id": "COA_11", "section": "COA", "topic": "Digital Logic", "question": "A multiplexer with n select lines can have how many maximum input lines?", "options": ["n", "2n", "n^2", "2^n"], "answer": "d", "explanation": "A MUX with n select lines chooses between 2^n data input lines.", "difficulty": "Medium" },
  { "id": "COA_12", "section": "COA", "topic": "Cache Memory", "question": "In a direct-mapped cache, how many cache blocks can a specific main memory block map to?", "options": ["Exactly 1", "Exactly 2", "Any block in a set", "Any block in the cache"], "answer": "a", "explanation": "Direct mapping forces a memory block into one specific modulo-calculated cache block.", "difficulty": "Hard" },
  { "id": "COA_13", "section": "COA", "topic": "Digital Logic", "question": "Which logic gate outputs 1 only when its inputs are different?", "options": ["AND", "OR", "XOR", "NAND"], "answer": "c", "explanation": "Exclusive OR (XOR) detects inequality between inputs.", "difficulty": "Easy" },
  { "id": "COA_14", "section": "COA", "topic": "Addressing Modes", "question": "In Immediate Addressing Mode, the operand is:", "options": ["In a register", "In memory", "Explicitly stated in the instruction", "Calculated at runtime"], "answer": "c", "explanation": "The data value itself is hardcoded directly into the operand field of the instruction.", "difficulty": "Easy" },
  { "id": "COA_15", "section": "COA", "topic": "Instruction Formats", "question": "A Stack Architecture CPU typically relies on which instruction format?", "options": ["Zero-address", "One-address", "Two-address", "Three-address"], "answer": "a", "explanation": "Stack architectures implicitly use the top of the stack for operands, requiring zero explicit addresses.", "difficulty": "Medium" },
  { "id": "COA_16", "section": "COA", "topic": "Cache Memory", "question": "Write-through cache policies usually result in:", "options": ["Slower write operations to main memory", "Stale data in main memory", "Faster writes than write-back", "No memory traffic"], "answer": "a", "explanation": "Write-through updates both cache and RAM simultaneously, ensuring consistency but slowing down writes.", "difficulty": "Medium" },
  { "id": "COA_17", "section": "COA", "topic": "Digital Logic", "question": "Flip-flops are primarily used to construct:", "options": ["Adders", "Multiplexers", "Registers", "Decoders"], "answer": "c", "explanation": "Flip-flops are 1-bit memory cells. Grouped together, they form CPU registers.", "difficulty": "Easy" },
  { "id": "COA_18", "section": "COA", "topic": "Pipelining", "question": "Data forwarding (or bypassing) is a hardware technique used to resolve:", "options": ["Structural hazards", "Control hazards", "Data hazards", "Cache misses"], "answer": "c", "explanation": "Forwarding passes ALU results directly back to ALU inputs to bypass register write delays.", "difficulty": "Hard" },

  // ALGORITHMS (16 Questions)
  { "id": "ALGO_1", "section": "Algorithms", "topic": "Traversals", "question": "Which data structure is fundamentally used to implement Depth First Search (DFS)?", "options": ["Queue", "Stack", "Heap", "Linked List"], "answer": "b", "explanation": "DFS explores deeply and backtracks, naturally mapping to LIFO Stack operations.", "difficulty": "Easy" },
  { "id": "ALGO_2", "section": "Algorithms", "topic": "Traversals", "question": "Which data structure is fundamentally used to implement Breadth First Search (BFS)?", "options": ["Queue", "Stack", "Heap", "Array"], "answer": "a", "explanation": "BFS explores layer by layer, naturally mapping to FIFO Queue operations.", "difficulty": "Easy" },
  { "id": "ALGO_3", "section": "Algorithms", "topic": "Binary Search Trees", "question": "An In-order traversal of a Binary Search Tree produces elements in:", "options": ["Random order", "Decreasing order", "Non-decreasing order", "Level order"], "answer": "c", "explanation": "In-order (Left-Root-Right) naturally processes smaller left elements before larger right ones.", "difficulty": "Easy" },
  { "id": "ALGO_4", "section": "Algorithms", "topic": "Greedy Algorithms", "question": "Which of the following problems requires Dynamic Programming and CANNOT be solved optimally with a Greedy approach?", "options": ["Fractional Knapsack", "Dijkstra's Shortest Path", "Kruskal's MST", "0/1 Knapsack"], "answer": "d", "explanation": "0/1 Knapsack involves taking whole items, leading to overlapping subproblems that defeat greedy heuristics.", "difficulty": "Medium" },
  { "id": "ALGO_5", "section": "Algorithms", "topic": "Greedy Algorithms", "question": "Kruskal's Algorithm uses which data structure to efficiently check for cycles?", "options": ["Priority Queue", "Disjoint Set (Union-Find)", "Hash Table", "Binary Search Tree"], "answer": "b", "explanation": "Disjoint sets track connected components. If two vertices belong to the same set, adding an edge creates a cycle.", "difficulty": "Medium" },
  { "id": "ALGO_6", "section": "Algorithms", "topic": "Dynamic Programming", "question": "What is the time complexity of solving Matrix Chain Multiplication using Dynamic Programming?", "options": ["O(n)", "O(n log n)", "O(n^2)", "O(n^3)"], "answer": "d", "explanation": "MCM using DP evaluates splits of subchains, taking O(n^3) time.", "difficulty": "Hard" },
  { "id": "ALGO_7", "section": "Algorithms", "topic": "Dynamic Programming", "question": "The core characteristic that makes a problem suitable for Dynamic Programming is:", "options": ["Requires a local optimum choice", "Has overlapping subproblems", "Can be solved recursively without memory", "Is NP-Complete"], "answer": "b", "explanation": "DP optimizes by storing the results of overlapping subproblems (memoization/tabulation).", "difficulty": "Easy" },
  { "id": "ALGO_8", "section": "Algorithms", "topic": "Greedy Algorithms", "question": "Dijkstra's algorithm relies on which data structure to repeatedly find the next closest vertex?", "options": ["Stack", "Min-Heap / Priority Queue", "Hash Map", "Disjoint Set"], "answer": "b", "explanation": "A Min-Heap allows extracting the vertex with the smallest distance in O(log V) time.", "difficulty": "Medium" },
  { "id": "ALGO_9", "section": "Algorithms", "topic": "Traversals", "question": "Which tree traversal is commonly used to safely delete an entire tree from memory?", "options": ["Pre-order", "In-order", "Post-order", "Level-order"], "answer": "c", "explanation": "Post-order (Left-Right-Root) ensures children are deleted before their parent node.", "difficulty": "Medium" },
  { "id": "ALGO_10", "section": "Algorithms", "topic": "Sorting", "question": "Which sorting algorithm consistently performs at O(n log n) in all cases (worst, average, best)?", "options": ["Quick Sort", "Merge Sort", "Insertion Sort", "Bubble Sort"], "answer": "b", "explanation": "Merge sort divides exactly in half and merges, guaranteeing O(n log n) regardless of array state.", "difficulty": "Easy" },
  { "id": "ALGO_11", "section": "Algorithms", "topic": "Dynamic Programming", "question": "The Longest Common Subsequence (LCS) problem is typically solved using:", "options": ["Greedy method", "Divide and Conquer", "Dynamic Programming", "Backtracking"], "answer": "c", "explanation": "LCS exhibits overlapping subproblems and optimal substructure, perfect for DP.", "difficulty": "Medium" },
  { "id": "ALGO_12", "section": "Algorithms", "topic": "Sorting", "question": "The worst-case time complexity of Quick Sort is:", "options": ["O(n)", "O(n log n)", "O(n^2)", "O(2^n)"], "answer": "c", "explanation": "If the pivot chosen is always the largest or smallest element (e.g., already sorted array), it degrades to O(n^2).", "difficulty": "Easy" },
  { "id": "ALGO_13", "section": "Algorithms", "topic": "Greedy Algorithms", "question": "Prim's Algorithm is used for:", "options": ["Shortest path routing", "Finding a Minimum Spanning Tree", "Topological sorting", "String matching"], "answer": "b", "explanation": "Prim's is a greedy algorithm that grows a single Minimum Spanning Tree vertex by vertex.", "difficulty": "Medium" },
  { "id": "ALGO_14", "section": "Algorithms", "topic": "Traversals", "question": "Which graph algorithm is used to find the shortest path in an unweighted graph?", "options": ["DFS", "BFS", "Dijkstra's", "Kruskal's"], "answer": "b", "explanation": "BFS expands evenly in all directions, naturally finding the shortest path in unweighted networks.", "difficulty": "Hard" },
  { "id": "ALGO_15", "section": "Algorithms", "topic": "Dynamic Programming", "question": "Memoization in Dynamic Programming refers to:", "options": ["Top-down approach storing results of expensive function calls", "Bottom-up approach using iterative tables", "Greedy selection", "Dividing into non-overlapping problems"], "answer": "a", "explanation": "Memoization caches recursive top-down results to avoid redundant calculations.", "difficulty": "Medium" },
  { "id": "ALGO_16", "section": "Algorithms", "topic": "Binary Search Trees", "question": "The time complexity to search an element in a balanced Binary Search Tree is:", "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"], "answer": "b", "explanation": "A balanced BST cuts the search space in half at each step, yielding logarithmic time.", "difficulty": "Easy" },

  // COMPUTER NETWORKS (5 Questions)
  { "id": "CN_1", "section": "Computer Networks", "topic": "OSI Model", "question": "Which layer of the OSI model is responsible for routing packets from the source to the destination?", "options": ["Data Link Layer", "Network Layer", "Transport Layer", "Session Layer"], "answer": "b", "explanation": "The Network layer handles logical addressing and routing.", "difficulty": "Easy" },
  { "id": "CN_2", "section": "Computer Networks", "topic": "OSI Model", "question": "Error detection and correction at the frame level is primarily the responsibility of the:", "options": ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"], "answer": "b", "explanation": "The Data Link layer frames data and performs physical addressing and error detection (MAC/LLC).", "difficulty": "Easy" },
  { "id": "CN_3", "section": "Computer Networks", "topic": "IP Addressing", "question": "How many bits constitute an IPv4 address?", "options": ["16", "32", "64", "128"], "answer": "b", "explanation": "IPv4 addresses are 32 bits long, typically written in dotted-decimal format.", "difficulty": "Easy" },
  { "id": "CN_4", "section": "Computer Networks", "topic": "IP Addressing", "question": "Which class of IP address uses the first octet for the network ID and the remaining three octets for the host ID?", "options": ["Class A", "Class B", "Class C", "Class D"], "answer": "a", "explanation": "Class A networks dedicate 8 bits to the network ID and 24 bits to the host ID.", "difficulty": "Easy" },
  { "id": "CN_5", "section": "Computer Networks", "topic": "Protocols", "question": "Which protocol operates at the Transport layer and provides connectionless, unacknowledged service?", "options": ["TCP", "UDP", "IP", "HTTP"], "answer": "b", "explanation": "UDP (User Datagram Protocol) is a connectionless, best-effort transport protocol.", "difficulty": "Easy" },

  // SOFTWARE ENGINEERING (5 Questions)
  { "id": "SE_1", "section": "Software Engineering", "topic": "SDLC Models", "question": "Which software development model emphasizes risk analysis at every phase?", "options": ["Waterfall Model", "Spiral Model", "Iterative Model", "RAD Model"], "answer": "b", "explanation": "The Spiral model explicitly includes risk assessment in each of its iterative loops.", "difficulty": "Medium" },
  { "id": "SE_2", "section": "Software Engineering", "topic": "Testing", "question": "Black-box testing primarily focuses on testing the:", "options": ["Internal logic", "Functional requirements", "Code structure", "Memory leaks"], "answer": "b", "explanation": "Black-box testing verifies functionality based on inputs and expected outputs without looking at internal code.", "difficulty": "Easy" },
  { "id": "SE_3", "section": "Software Engineering", "topic": "Testing", "question": "Which testing is performed first after individual components are merged?", "options": ["Unit Testing", "System Testing", "Integration Testing", "Acceptance Testing"], "answer": "c", "explanation": "Integration testing checks the interfaces and interactions between combined modules.", "difficulty": "Easy" },
  { "id": "SE_4", "section": "Software Engineering", "topic": "Metrics", "question": "Cyclomatic complexity is a software metric used to measure:", "options": ["Hardware requirements", "Logical complexity", "Execution time", "Team size"], "answer": "b", "explanation": "Cyclomatic complexity measures the number of linearly independent paths through a program's source code.", "difficulty": "Medium" },
  { "id": "SE_5", "section": "Software Engineering", "topic": "SDLC Models", "question": "In the Waterfall model, which phase immediately follows Requirements Analysis?", "options": ["Coding", "System Design", "Testing", "Maintenance"], "answer": "b", "explanation": "Once requirements are locked, the architecture and system design phase begins.", "difficulty": "Easy" },

  // PROGRAMMING (5 Questions)
  { "id": "PROG_1", "section": "Programming", "topic": "OOP Concepts", "question": "Which OOP concept hides internal implementation details and exposes only necessary functionalities?", "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"], "answer": "d", "explanation": "Abstraction hides background details, while encapsulation binds data and functions together.", "difficulty": "Medium" },
  { "id": "PROG_2", "section": "Programming", "topic": "OOP Concepts", "question": "Method overriding is an example of:", "options": ["Compile-time polymorphism", "Run-time polymorphism", "Encapsulation", "Data hiding"], "answer": "b", "explanation": "Overriding allows a subclass to provide a specific implementation of a method at runtime (Dynamic Binding).", "difficulty": "Medium" },
  { "id": "PROG_3", "section": "Programming", "topic": "Java Basics", "question": "In Java, which keyword is used to prevent a class from being inherited?", "options": ["static", "abstract", "final", "private"], "answer": "c", "explanation": "The 'final' keyword on a class strictly prohibits any other class from extending it.", "difficulty": "Easy" },
  { "id": "PROG_4", "section": "Programming", "topic": "OOP Concepts", "question": "Which principle states that a subclass must be substitutable for its base class?", "options": ["Open-Closed Principle", "Liskov Substitution Principle", "Interface Segregation", "Dependency Inversion"], "answer": "b", "explanation": "Liskov Substitution Principle (LSP) ensures derived classes extend base classes without changing behavior.", "difficulty": "Hard" },
  { "id": "PROG_5", "section": "Programming", "topic": "Pointers", "question": "Which programming language heavily features manual pointer arithmetic?", "options": ["Java", "Python", "C", "C#"], "answer": "c", "explanation": "C allows direct memory manipulation using pointer arithmetic.", "difficulty": "Easy" }
];

const paper2TopicNotes = {
  'Language Hierarchy': {
    summary: 'The strict subset hierarchy defining the computational power of formal languages and their corresponding machine acceptors.',
    formula: 'Regular ⊂ DCFL ⊂ CFL ⊂ CSL ⊂ Recursive ⊂ RE',
    details: '<b>Subset Rule:</b> Any language that belongs to a restricted class automatically belongs to all broader classes above it. Regular languages are closed under union, intersection, and complement. CFLs are NOT closed under intersection or complement.',
    example: 'A Regular language can be parsed by a DFA. Because Regular ⊂ CFL, it can inherently be parsed by a PDA as well. However, the reverse is strictly false.'
  },
  'Pushdown Automata': {
    summary: 'Finite automata augmented with a Stack data structure, capable of recognizing Context-Free Languages.',
    formula: 'Transition = δ(Current State, Input Symbol, Top of Stack Symbol)',
    details: '<b>Determinism:</b> Unlike Finite Automata, non-determinism adds strict power here. NPDAs can recognize generic Context-Free Languages (like even palindromes ww^R), whereas DPDAs can only recognize DCFLs (like a^n b^n).',
    example: 'To accept a^n b^n, the PDA pushes an "a" to the stack for every "a" read. Upon seeing "b", it pops an "a". If the stack is empty exactly when the string ends, it accepts.'
  },
  'Grammar Rules': {
    summary: 'The syntactic production rules (V → W) that generate the strings belonging to a language.',
    formula: 'Right Linear: A → aB or A → a. Left Linear: A → Ba or A → a.',
    details: '<b>Chomsky Normal Form (CNF):</b> Requires exactly two non-terminals (A → BC) or exactly one terminal (A → a). Regular grammars strictly forbid non-terminals from being sandwiched between terminals.',
    example: 'S → aSb is a Context-Free production. S → aS is a Regular production (specifically, right-linear).'
  },
  'Turing Machines': {
    summary: 'The most powerful mathematical model of computation, featuring an infinite read/write tape.',
    formula: 'Transition = δ(State, Read Symbol) → (New State, Write Symbol, Move L/R)',
    details: '<b>Halting Problem:</b> It is undecidable to write a general algorithm that determines if an arbitrary Turing Machine will halt. A language is <i>Recursive</i> if the TM always halts and decides it.',
    example: 'A Universal Turing Machine takes the description of another TM and simulates it—forming the theoretical basis of all modern programmable computers.'
  },
  'Automata Transitions': {
    summary: 'The mathematical mappings that dictate how a state machine shifts from one state to another.',
    formula: 'DFA Transition: Q × Σ → Q. NFA Transition: Q × Σ → P(Q)',
    details: '<b>Subset Construction:</b> Every NFA can be converted to an equivalent DFA using Powerset Construction. The resulting DFA may have up to 2^n states in the worst-case scenario.',
    example: 'Pumping Lemmas are adversarial proofs used specifically to transition a language out of a class (e.g., proving a language is NOT regular).'
  },
  'Integrity Constraints': {
    summary: 'Strict relational database rules ensuring the accuracy, uniqueness, and validity of stored data.',
    formula: 'Entity Integrity: PK ≠ NULL. Referential Integrity: FK ⊆ PK (or NULL).',
    details: '<b>Enforcement:</b> Entity integrity ensures every row is uniquely identifiable. Referential integrity ensures that orphaned child records cannot exist if their parent in the base table is deleted.',
    example: 'If an Employee table has a Dept_ID (Foreign Key), it must match an existing ID in the Department table, or remain NULL if the employee is unassigned.'
  },
  'ER Diagrams': {
    summary: 'Entity-Relationship Diagrams: the architectural blueprints mapping database entities to their relational links.',
    formula: 'Entity = Rectangle. Weak Entity = Double Rectangle. Identifying Relation = Double Diamond.',
    details: '<b>Attributes:</b> Standard attributes use single ellipses. Derived attributes (computed on the fly) use dashed ellipses. Multivalued attributes (like a list of phone numbers) use double ellipses.',
    example: 'Age is a derived attribute (dashed ellipse) because it is dynamically calculated from the Date of Birth base attribute.'
  },
  'SQL Clauses': {
    summary: 'The structured syntax sequence used to retrieve, filter, group, and sort database records.',
    formula: 'SELECT (cols) FROM (table) [WHERE condition] [GROUP BY] [HAVING] [ORDER BY]',
    details: '<b>Execution Order:</b> FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. The SELECT and FROM clauses are strictly mandatory. All others are optional.',
    example: 'SELECT Name FROM Users WHERE Age > 18 ORDER BY Name DESC;'
  },
  'Normalization': {
    summary: 'The process of structuring tables to eliminate data redundancy and insertion/deletion anomalies.',
    formula: '1NF (Atomic) → 2NF (No Partial Dep) → 3NF (No Transitive Dep) → BCNF (Superkeys Only)',
    details: '<b>Dependencies:</b> 2NF targets composite keys, ensuring non-prime attributes rely on the whole key. 3NF ensures non-prime attributes do not rely on other non-prime attributes.',
    example: 'Moving a "Department Name" column out of the "Employees" table and into a dedicated "Departments" table fulfills 3NF.'
  },
  'Transactions': {
    summary: 'A logical unit of database processing that must strictly adhere to the ACID properties.',
    formula: 'ACID = Atomicity, Consistency, Isolation, Durability',
    details: '<b>Deadlocks:</b> Occur when transactions wait circularly for locks held by each other. Rollbacks are used to undo a transaction to preserve consistency during failures.',
    example: 'A bank transfer must be Atomic: if deducting $50 from Account A succeeds but adding to Account B fails, the whole transaction must rollback.'
  },
  'Relational Algebra': {
    summary: 'The procedural query language that forms the mathematical foundation of SQL operations.',
    formula: 'Selection (σ): Filters rows. Projection (π): Filters columns.',
    details: '<b>Cartesian Product:</b> Combining two tables of cardinality M and N yields M * N rows. Selection operations without projection return all columns by default.',
    example: 'π_Name (σ_Age>18 (Users)) translates to SELECT Name FROM Users WHERE Age > 18.'
  },
  'Process States': {
    summary: 'The distinct lifecycle phases an operating system process moves through during execution.',
    formula: 'New → Ready → Running → Waiting → Terminated',
    details: '<b>Memory Hierarchy:</b> Active states (Ready, Running, Waiting/Blocked) are managed in Primary Memory (RAM). The New and Terminated states reside in Secondary Storage.',
    example: 'If a Running process requests disk I/O, it is moved to the Waiting state until the hardware interrupt signals completion.'
  },
  'Schedulers': {
    summary: 'The OS components responsible for marshaling processes between queues to optimize CPU utilization.',
    formula: 'Long-Term (Job), Short-Term (CPU), Mid-Term (Swapping)',
    details: '<b>Distinctions:</b> The Long-Term scheduler controls the degree of multiprogramming. The Short-Term scheduler executes frequently to swap running processes. Mid-Term handles RAM thrashing.',
    example: 'When RAM is full, the Mid-Term scheduler swaps idle Waiting processes out to the disk to free up memory.'
  },
  'System Calls': {
    summary: 'The programmatic API used by user-space applications to request privileged OS kernel services.',
    formula: 'User Mode (Bit 1) → Trap/Interrupt → Kernel Mode (Bit 0)',
    details: '<b>Mechanism:</b> System calls are software interrupts that safely elevate privileges. Examples include fork() to create processes, and exec() to load a binary.',
    example: 'A Python script writing to a text file triggers a system call under the hood, transferring control to the OS to interface with the hard drive.'
  },
  'Memory Management': {
    summary: 'The OS subsystem mapping logical addresses to physical memory and mitigating fragmentation.',
    formula: 'Logical Bits = Page Num Bits + Offset Bits. Process Size = Pages × Page Size.',
    details: '<b>Paging vs Segmentation:</b> Paging utilizes fixed-size blocks (pages/frames) and causes internal fragmentation. The Translation Lookaside Buffer (TLB) caches recent page mappings.',
    example: 'If Address Space = 4096 (12 bits) and Page Size = 512 (9 bits), then the first 3 bits designate the page number.'
  },
  'Deadlocks': {
    summary: 'A system freeze caused when processes wait circularly for resources locked by each other.',
    formula: 'Coffman Conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait.',
    details: '<b>Prevention vs Avoidance:</b> Prevention invalidates one of the four conditions. Avoidance (like Banker’s Algorithm) simulates future allocations to guarantee a safe execution state.',
    example: 'If P1 holds Disk A and waits for Disk B, while P2 holds Disk B and waits for Disk A, a deadlock occurs.'
  },
  'Cache Memory': {
    summary: 'Ultra-fast SRAM positioned between the CPU registers and Main Memory to mask latency.',
    formula: 'Direct Mapping: Cache Block = Memory Block MOD Total Cache Blocks',
    details: '<b>Locality:</b> Cache exploits Temporal Locality (re-accessing identical data) and Spatial Locality (accessing contiguous data). Write-through policies immediately update RAM but are slower.',
    example: 'A simple `for` loop heavily relies on Temporal Locality, allowing the CPU to repeatedly fetch instructions from the blazing-fast cache.'
  },
  'Pipelining': {
    summary: 'An architectural technique overlapping the fetch-decode-execute stages to achieve instruction-level parallelism.',
    formula: 'Ideal CPI (Cycles Per Instruction) = 1. Speedup = Total Sequential Time / Total Pipeline Time.',
    details: '<b>Hazards:</b> Data hazards happen when operands are not yet ready (fixed by data forwarding). Control hazards occur on branch instructions (fixed by branch prediction or flushing).',
    example: 'In a 5-stage pipeline, once it is completely filled on the 5th cycle, a new instruction completes executing on every subsequent single clock cycle.'
  },
  'Instruction Formats': {
    summary: 'The binary layout dictating how the CPU interprets operational commands and their operands.',
    formula: 'Format = [Opcode] [Addressing Mode] [Operand / Address]',
    details: '<b>Architectures:</b> 3-address machines specify two sources and a destination. Stack architectures use 0-address instructions because operands are implicitly at the top of the stack.',
    example: 'ADD R1, R2, R3 (Add R2 and R3, store in R1) is a typical 3-address instruction.'
  },
  'Addressing Modes': {
    summary: 'The varied mechanisms used by instructions to locate and fetch the actual data operands.',
    formula: 'Immediate (Hardcoded), Register (In CPU), Direct (In RAM), Indexed (Base + Offset).',
    details: '<b>Usage:</b> Immediate mode is fastest as data is embedded. Register mode is ultra-fast. Indexed mode is mathematically optimal for traversing arrays.',
    example: '`MOV R1, #50` uses Immediate mode. `MOV R1, R2` uses Register mode.'
  },
  'Digital Logic': {
    summary: 'The foundational boolean gates and combinational/sequential circuits powering hardware.',
    formula: 'Multiplexer = 2^n input lines to 1 output line. XOR = A\'B + AB\'.',
    details: '<b>Circuits:</b> Combinational circuits (Adders, MUX) rely purely on present inputs. Sequential circuits (Flip-Flops, Registers) rely on present inputs AND past states via a clock.',
    example: 'To add two 3-bit numbers (max 7+7=14), the hardware adder requires exactly 4 output bit lines.'
  },
  'Traversals': {
    summary: 'Algorithmic paradigms for systematically visiting every node in a graph or tree data structure.',
    formula: 'DFS = Stack (LIFO). BFS = Queue (FIFO).',
    details: '<b>Applications:</b> BFS guarantees finding the shortest path in unweighted graphs. Post-order tree traversals are ideal for safely deleting nodes from leaves to root.',
    example: 'An In-order traversal (Left → Root → Right) of a Binary Search Tree produces elements strictly in non-decreasing sorted order.'
  },
  'Binary Search Trees': {
    summary: 'A hierarchical tree where left children are strictly smaller and right children are strictly larger.',
    formula: 'Search Time = O(log n) if balanced, O(n) worst case (skewed).',
    details: '<b>Balancing:</b> AVL or Red-Black trees automatically rotate nodes upon insertion to maintain a balanced height, preventing O(n) degradation.',
    example: 'Searching for 50 in a balanced BST cuts the remaining search space in half at every single step down the tree.'
  },
  'Greedy Algorithms': {
    summary: 'An optimization paradigm that makes the absolute best local choice at every step without looking back.',
    formula: 'Dijkstra = Shortest Path (Min-Heap). Kruskal/Prim = MST (Disjoint Set).',
    details: '<b>Limitations:</b> Greedy algorithms work flawlessly for Fractional Knapsack, but completely fail on 0/1 Knapsack where choices impact future overlapping options.',
    example: 'Kruskal’s Algorithm iteratively picks the cheapest global edge. It uses a Disjoint Set to instantly verify if adding that edge would form an invalid cycle.'
  },
  'Dynamic Programming': {
    summary: 'A hyper-optimized paradigm that aggressively caches the results of overlapping recursive subproblems.',
    formula: 'Memoization (Top-Down Caching) or Tabulation (Bottom-Up Table Building).',
    details: '<b>Use Cases:</b> Absolutely mandatory for 0/1 Knapsack, Longest Common Subsequence, and Matrix Chain Multiplication (which has a time complexity of O(n^3)).',
    example: 'Instead of recursively calculating Fibonacci(5) by computing Fibonacci(3) multiple times, DP computes it once and simply looks up the answer instantly thereafter.'
  },
  'Sorting': {
    summary: 'The algorithmic organization of elements into a strictly increasing or decreasing linear sequence.',
    formula: 'Merge Sort = O(n log n) Always. Quick Sort = O(n log n) Avg, O(n^2) Worst.',
    details: '<b>Mechanisms:</b> Merge Sort physically divides the array in half recursively. Quick Sort pivots data around a chosen element. If the pivot is terrible, Quick Sort degrades to O(n^2).',
    example: 'Because it splits the array perfectly in half every time regardless of data distribution, Merge Sort guarantees a worst-case time complexity of O(n log n).'
  },
  'OSI Model': {
    summary: 'The conceptual framework used to describe the functions of a networking system across 7 abstract layers.',
    formula: 'Please Do Not Throw Sausage Pizza Away (Physical, Data Link, Network, Transport, Session, Presentation, Application)',
    details: '<b>Routing:</b> The Network layer handles logical IP addressing and routing. The Data Link layer handles physical MAC addressing and framing.',
    example: 'A router operates primarily at the Network Layer (Layer 3), while a switch operates at the Data Link Layer (Layer 2).'
  },
  'IP Addressing': {
    summary: 'The logical addressing scheme that uniquely identifies devices on a TCP/IP network.',
    formula: 'IPv4 = 32 bits (4 octets). IPv6 = 128 bits.',
    details: '<b>Classes:</b> Class A (0-127) uses 8 bits for network ID. Class B (128-191) uses 16 bits. Class C (192-223) uses 24 bits.',
    example: 'The address 192.168.1.1 is a Class C address commonly used for local home networks.'
  },
  'Protocols': {
    summary: 'The standardized rules dictating how data is transmitted and received over a network.',
    formula: 'TCP = Connection-Oriented, Reliable. UDP = Connectionless, Fast.',
    details: '<b>Use Cases:</b> Use TCP for web browsing (HTTP) where data integrity is critical. Use UDP for video streaming or gaming where speed is preferred over reliability.',
    example: 'DNS requests heavily utilize UDP to rapidly query IP addresses without the overhead of establishing a handshake.'
  },
  'SDLC Models': {
    summary: 'The standardized frameworks used to guide the Software Development Life Cycle from conception to deployment.',
    formula: 'Waterfall (Sequential) vs Agile (Iterative) vs Spiral (Risk-Driven).',
    details: '<b>Phases:</b> Most models follow Requirements → Design → Implementation → Testing → Deployment → Maintenance.',
    example: 'The Spiral model is highly preferred for massive, complex projects (like an OS build) because it explicitly focuses on risk analysis during every loop.'
  },
  'Testing': {
    summary: 'The validation phase ensuring software meets requirements and functions without defects.',
    formula: 'Unit (Component) → Integration (Combined) → System (End-to-End) → Acceptance (User).',
    details: '<b>Approaches:</b> Black-Box focuses on inputs and outputs without seeing the code. White-Box requires deep understanding of internal structures and logic paths.',
    example: 'A QA engineer entering bad passwords into a login screen to check if it displays an error is performing Black-Box testing.'
  },
  'Metrics': {
    summary: 'Quantitative measurements used to estimate software complexity, effort, and quality.',
    formula: 'Cyclomatic Complexity = E - N + 2P (Edges - Nodes + 2*Connected Components)',
    details: '<b>Purpose:</b> Metrics help project managers estimate costs (e.g., COCOMO model) and developers gauge code maintainability.',
    example: 'A function with a massive switch statement and 20 if-conditions will have extremely high Cyclomatic Complexity.'
  },
  'OOP Concepts': {
    summary: 'Object-Oriented Programming paradigms that organize code around distinct entities holding data and behavior.',
    formula: '4 Pillars: Encapsulation, Abstraction, Inheritance, Polymorphism.',
    details: '<b>Polymorphism:</b> Compile-time (Method Overloading) vs Run-time (Method Overriding using Dynamic Binding).',
    example: 'Abstraction is driving a car using the steering wheel and pedals without needing to understand the internal combustion engine.'
  },
  'Java Basics': {
    summary: 'Core language principles of the highly popular, platform-independent Java programming language.',
    formula: 'Write Once, Run Anywhere (JVM).',
    details: '<b>Keywords:</b> The `final` keyword prevents variable reassignment, method overriding, or class inheritance. The `static` keyword belongs to the class, not instances.',
    example: 'The entry point `public static void main` is static because the JVM must invoke it without instantiating an object of the class.'
  },
  'Pointers': {
    summary: 'Variables that store the physical memory addresses of other variables or functions.',
    formula: 'Pointer Definition: int *p = &var. Dereferencing: *p.',
    details: '<b>Languages:</b> C and C++ heavily utilize manual pointer arithmetic. Java completely removes manual pointers to enhance security and memory safety.',
    example: 'If `var` is stored at memory address 0x1A4, then the pointer `p` holds the value 0x1A4.'
  }
};
